[features]
seeds = false
skip-lint = false
[programs.mainnet]
atomic_swap_spl = "D11bXyFQhaLd9B3U2pYDag5EUVzzenQJnWmSL8PU9dkg"
[programs.devnet]
atomic_swap_spl = "4NJ18xSDkkU9Pt8rAB9zwfYzgP7nmW4Wat9ZfuVT8mrU"
[programs.localnet]
atomic_swap_spl = "4NJ18xSDkkU9Pt8rAB9zwfYzgP7nmW4Wat9ZfuVT8mrU"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://solana-devnet.g.alchemy.com/v2/VQbD5BPThF22JCKKu2kdh2W5tEg64Uqg"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 test/AtomicSwapS.ts"