name: Tests Analysis

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker Desktop
        run: |
          sudo apt-get update
          sudo apt-get install \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Start Docker
        run: sudo service docker start

      - name: Install and run Nigiri
        run: |
          curl https://getnigiri.vulpem.com | bash
          nigiri start

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.16.3/install)"
          source ~/.profile
          solana-keygen new --no-passphrase --force
          solana config set --url http://localhost:8899

      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y pkg-config build-essential libudev-dev libssl-dev
          avm install latest
          avm use latest

      - name: Install Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Project Dependencies
        run: yarn install

      - name: Run Bitcoin Tests
        run: npx hardhat test test/AtomicSwapB.ts

      - name: Run Ethereum Tests
        run: npx hardhat test test/AtomicSwapE.ts

      - name: Run Solana Tests
        run: anchor test

      - name: Integration Tests
        run: npx hardhat test test/AtomicSwap.ts
