name: Tests Analysis

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Project Dependencies
        run: yarn install

      - name: Run Tests
        run: npx hardhat test
