name: Tests Analysis

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker Desktop
        run: |
          sudo apt-get update
          sudo apt-get install \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Start Docker
        run: sudo service docker start

      - name: Install and run Nigiri
        run: |
          curl https://getnigiri.vulpem.com | bash
          nigiri start

      - name: Install Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Project Dependencies
        run: yarn install
  
      - name: Run Bitcoin Tests
        run: npx hardhat test test/AtomicSwapB.ts

      - name: Run Ethereum Tests
        run: npx hardhat test test/AtomicSwapE.ts

      - name: Integration Tests
        run: npx hardhat test test/AtomicSwap.ts

  build2:
    runs-on: ubuntu-latest
    container: backpackapp/build:v0.28.0

    steps:
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules/
          key: node-modules-${{ runner.os }}-build-18.16.0
      - name: Install node_modules
        run: yarn
        shell: bash
      - name: Create keypair
        run: solana-keygen new --no-bip39-passphrase
        shell: bash
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: anchor test
        shell: bash
